package com.danioliveira.taskmanager.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF575992)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE1E0FF)
val onPrimaryContainerLight = Color(0xFF3F4178)
val secondaryLight = Color(0xFF575992)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE1E0FF)
val onSecondaryContainerLight = Color(0xFF3F4178)
val tertiaryLight = Color(0xFF69548D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFECDCFF)
val onTertiaryContainerLight = Color(0xFF513C73)
val errorLight = Color(0xFF904A43)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF73332D)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFCF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE4E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC8C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF3EFF7)
val inversePrimaryLight = Color(0xFFC0C1FF)
val surfaceDimLight = Color(0xFFDCD9E0)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F2FA)
val surfaceContainerLight = Color(0xFFF0ECF4)
val surfaceContainerHighLight = Color(0xFFEAE7EF)
val surfaceContainerHighestLight = Color(0xFFE4E1E9)

val primaryDark = Color(0xFFC0C1FF)
val onPrimaryDark = Color(0xFF292A60)
val primaryContainerDark = Color(0xFF3F4178)
val onPrimaryContainerDark = Color(0xFFE1E0FF)
val secondaryDark = Color(0xFFC0C1FF)
val onSecondaryDark = Color(0xFF292A60)
val secondaryContainerDark = Color(0xFF3F4178)
val onSecondaryContainerDark = Color(0xFFE1E0FF)
val tertiaryDark = Color(0xFFD4BBFC)
val onTertiaryDark = Color(0xFF3A255B)
val tertiaryContainerDark = Color(0xFF513C73)
val onTertiaryContainerDark = Color(0xFFECDCFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF561E19)
val errorContainerDark = Color(0xFF73332D)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC8C5D0)
val outlineDark = Color(0xFF918F9A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF575992)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39383F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)






