name: server
description: Server for the task manager application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.3
  json_annotation: ^4.9.0
  shared:
    path: ../shared
  postgres: ^2.6.3
  provider: ^6.1.1
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  dotenv: ^4.2.0
  shelf_test_handler: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^5.1.1
  test: ^1.26.1
  mockito: ^5.4.6