name: server
description: A server for the task manager application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  jwt_decoder: ^2.0.1
  shared:
    path: ../shared
  postgres: ^2.6.3
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.0
  dotenv: ^4.2.0
  http: ^1.1.0 # Add http package
  shelf_test_handler: ^2.0.2
  testainers: ^0.2.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^5.1.1
  test: ^1.26.1
  mockito: ^5.4.6