name: server
description: A server for the task manager application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shared:
    path: ../shared
  postgres: ^2.6.3
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.0
  dotenv: ^4.2.0
  http: ^1.1.0
  uuid: ^4.5.1
  prometheus_client: ^1.0.0+1
  prometheus_client_shelf: ^1.0.0+1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.0
  shelf_test_handler: ^2.0.2