name: shared
description: Shared code between app and server.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^5.1.1 